---
- name: get service status of a server that exists
  win_service_status:
    name: winrm
  register: existing_service_status

- name: debug result of service that exists
  debug:
    msg: "{{ existing_service_status }}"

- name: get service status of a server that does not exists
  win_service_status:
    name: testservice
  register: non_existing_service_status

- name: debug result of service that does not exists
  debug:
    msg: "{{ non_existing_service_status }}"
